name: stanley-racing
region: sgp

services:
- name: web
  dockerfile_path: Dockerfile.web
  github:
    repo: your-username/stanley-repo
    branch: main
    deploy_on_push: true
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  health_check:
    http_path: /health
  envs:
  - key: USE_POSTGRES
    value: "true"
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
  - key: JWT_SECRET_KEY
    type: SECRET
    value: "your-secret-key-here"
  - key: SMTP_SERVER
    value: "smtp.gmail.com"
  - key: SMTP_PORT
    value: "587"
  - key: SMTP_USERNAME
    type: SECRET
    value: "your-smtp-username"
  - key: SMTP_PASSWORD
    type: SECRET
    value: "your-smtp-password"
  - key: ALERT_EMAIL
    value: "adamsalistair1978@gmail.com"

- name: worker
  dockerfile_path: Dockerfile.worker
  github:
    repo: your-username/stanley-repo
    branch: main
    deploy_on_push: true
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: USE_POSTGRES
    value: "true"
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
  - key: TWILIO_ACCOUNT_SID
    type: SECRET
    value: "your-twilio-sid"
  - key: TWILIO_AUTH_TOKEN
    type: SECRET
    value: "your-twilio-token"
  - key: TWILIO_FROM_PHONE
    value: "+1234567890"
  - key: ALERT_PHONE
    value: "+61417676973"
  - key: SMTP_SERVER
    value: "smtp.gmail.com"
  - key: SMTP_PORT
    value: "587"
  - key: SMTP_USERNAME
    type: SECRET
    value: "your-smtp-username"
  - key: SMTP_PASSWORD
    type: SECRET
    value: "your-smtp-password"
  - key: ALERT_EMAIL
    value: "adamsalistair1978@gmail.com"

databases:
- name: db
  engine: PG
  production: false
  cluster_name: stanley-dbase

